name: Deploy Images to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2 # Change this to your AWS region
  ECR_REPOSITORY: awsessentials/common # Change this to your ECR repository name
  EC2_HOST: 3.107.6.224 # Change this to your EC2 host'

jobs:
  deployImages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull Docker Image from ECR
        uses: docker/setup-buildx-action@v2

      - name: Copy Docker Image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'docker_image.tar'
          target: '~/'

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i ~/docker_image.tar
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 3000:3000 ${{ env.ECR_REPOSITORY }}:latest
            docker image prune -af
